export const ActionTypes = {
    // Auth Actions
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    
    // Project Actions
    SET_PROJECTS: 'SET_PROJECTS',
    ADD_PROJECT: 'ADD_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',
    
    // Symbol Actions
    SET_SYMBOLS: 'SET_SYMBOLS',
    ADD_SYMBOL: 'ADD_SYMBOL',
    UPDATE_SYMBOL: 'UPDATE_SYMBOL',
    DELETE_SYMBOL: 'DELETE_SYMBOL',
    
    // Drawing Actions
    SET_DRAWINGS: 'SET_DRAWINGS',
    UPDATE_DRAWING_STATUS: 'UPDATE_DRAWING_STATUS',
    SET_PROCESSING_STATUS: 'SET_PROCESSING_STATUS',
  
    // UI Actions
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR'
  };
